export const offers = [
  {
    id: 'offer6353',
    firstImgSrc: 'assets/lgt/offers/offer6353/firstImgSrc/img.png',
    offer_name: 'ROYALTON RIVIERA CANCUN RESORT & SPA 5* | ALL INCLUSIVE',
    destination_detail: 'Carretera Federal 307 Tulum-Cancun, Puerto Morelos, Mexic',
    destination_city_name: 'Cancun',
    destination_type: 'Exotic',
    revelion: '',
    package_details: 'Pachet Punta Cana - Zbor + Cazare & Masa + Transfer',
    price: 1341,
    lgt_http: 'https://lgt.ro/oferta-item/royalton-riviera-cancun-resort-spa-5/'
  },
  {
  id: 'offer6354',
    firstImgSrc: 'assets/lgt/offers/offer6354/firstImgSrc/img.png',
    offer_name: 'NOW ONYX PUNTA CANA 5* | ALL INCLUSIVE – REVELION 2021',
    destination_detail: 'Uvero Alto, Punta Cana, Dominican Republic',
    destination_city_name: 'Punta Cana',
    destination_type: 'Exotic',
    revelion: 'Revelion',
    package_details: 'Pachet Punta Cana - Zbor + Cazare & Masa + Transfer',
    price: 1341,
    lgt_http: 'https://lgt.ro/oferta-item/now-onyx-punta-cana-5/'
  },
  {
  id: 'offer6355',
    firstImgSrc: 'assets/lgt/offers/offer6355/firstImgSrc/img.png',
    offer_name: 'HARBOR CLUB ST LUCIA, CURIO COLLECTION BY HILTON 4* | ALL INCLUSIVE',
    destination_detail: 'Rodney Bay, Gros Islet, Saint Lucia',
    destination_city_name: 'Saint Lucia',
    destination_type: '',
    revelion: '',
    package_details: 'Pachet St. Lucia - Zbor + Cazare & Masa + Transfer',
    price: 1341,
    lgt_http: 'https://lgt.ro/oferta-item/royalton-riviera-cancun-resort-spa-5/'
  },
  {
    id: 'offer6353',
    firstImgSrc: 'assets/lgt/offers/offer6353/firstImgSrc/img.png',
    offer_name: 'ROYALTON RIVIERA CANCUN RESORT & SPA 5* | ALL INCLUSIVE',
    destination_detail: 'Carretera Federal 307 Tulum-Cancun, Puerto Morelos, Mexic',
    destination_city_name: 'Cancun',
    destination_type: 'Exotic',
    revelion: '',
    package_details: 'Pachet Punta Cana - Zbor + Cazare & Masa + Transfer',
    price: 1341,
    lgt_http: 'https://lgt.ro/oferta-item/royalton-riviera-cancun-resort-spa-5/'
  },
  {
  id: 'offer6354',
    firstImgSrc: 'assets/lgt/offers/offer6354/firstImgSrc/img.png',
    offer_name: 'NOW ONYX PUNTA CANA 5* | ALL INCLUSIVE – REVELION 2021',
    destination_detail: 'Uvero Alto, Punta Cana, Dominican Republic',
    destination_city_name: 'Punta Cana',
    destination_type: 'Exotic',
    revelion: 'Revelion',
    package_details: 'Pachet Punta Cana - Zbor + Cazare & Masa + Transfer',
    price: 1341,
    lgt_http: 'https://lgt.ro/oferta-item/now-onyx-punta-cana-5/'
  },
  {
  id: 'offer6355',
    firstImgSrc: 'assets/lgt/offers/offer6355/firstImgSrc/img.png',
    offer_name: 'HARBOR CLUB ST LUCIA, CURIO COLLECTION BY HILTON 4* | ALL INCLUSIVE',
    destination_detail: 'Rodney Bay, Gros Islet, Saint Lucia',
    destination_city_name: 'Saint Lucia',
    destination_type: '',
    revelion: '',
    package_details: 'Pachet St. Lucia - Zbor + Cazare & Masa + Transfer',
    price: 1341,
    lgt_http: 'https://lgt.ro/oferta-item/royalton-riviera-cancun-resort-spa-5/'
  },
  {
    id: 'offer6353',
    firstImgSrc: 'assets/lgt/offers/offer6353/firstImgSrc/img.png',
    offer_name: 'ROYALTON RIVIERA CANCUN RESORT & SPA 5* | ALL INCLUSIVE',
    destination_detail: 'Carretera Federal 307 Tulum-Cancun, Puerto Morelos, Mexic',
    destination_city_name: 'Cancun',
    destination_type: 'Exotic',
    revelion: '',
    package_details: 'Pachet Punta Cana - Zbor + Cazare & Masa + Transfer',
    price: 1341,
    lgt_http: 'https://lgt.ro/oferta-item/royalton-riviera-cancun-resort-spa-5/'
  },
  {
  id: 'offer6354',
    firstImgSrc: 'assets/lgt/offers/offer6354/firstImgSrc/img.png',
    offer_name: 'NOW ONYX PUNTA CANA 5* | ALL INCLUSIVE – REVELION 2021',
    destination_detail: 'Uvero Alto, Punta Cana, Dominican Republic',
    destination_city_name: 'Punta Cana',
    destination_type: 'Exotic',
    revelion: 'Revelion',
    package_details: 'Pachet Punta Cana - Zbor + Cazare & Masa + Transfer',
    price: 1341,
    lgt_http: 'https://lgt.ro/oferta-item/now-onyx-punta-cana-5/'
  },
  {
  id: 'offer6355',
    firstImgSrc: 'assets/lgt/offers/offer6355/firstImgSrc/img.png',
    offer_name: 'HARBOR CLUB ST LUCIA, CURIO COLLECTION BY HILTON 4* | ALL INCLUSIVE',
    destination_detail: 'Rodney Bay, Gros Islet, Saint Lucia',
    destination_city_name: 'Saint Lucia',
    destination_type: '',
    revelion: '',
    package_details: 'Pachet St. Lucia - Zbor + Cazare & Masa + Transfer',
    price: 1341,
    lgt_http: 'https://lgt.ro/oferta-item/royalton-riviera-cancun-resort-spa-5/'
  },
  {
    id: 'offer6353',
    firstImgSrc: 'assets/lgt/offers/offer6353/firstImgSrc/img.png',
    offer_name: 'ROYALTON RIVIERA CANCUN RESORT & SPA 5* | ALL INCLUSIVE',
    destination_detail: 'Carretera Federal 307 Tulum-Cancun, Puerto Morelos, Mexic',
    destination_city_name: 'Cancun',
    destination_type: 'Exotic',
    revelion: '',
    package_details: 'Pachet Punta Cana - Zbor + Cazare & Masa + Transfer',
    price: 1341,
    lgt_http: 'https://lgt.ro/oferta-item/royalton-riviera-cancun-resort-spa-5/'
  },
  {
  id: 'offer6354',
    firstImgSrc: 'assets/lgt/offers/offer6354/firstImgSrc/img.png',
    offer_name: 'NOW ONYX PUNTA CANA 5* | ALL INCLUSIVE – REVELION 2021',
    destination_detail: 'Uvero Alto, Punta Cana, Dominican Republic',
    destination_city_name: 'Punta Cana',
    destination_type: 'Exotic',
    revelion: 'Revelion',
    package_details: 'Pachet Punta Cana - Zbor + Cazare & Masa + Transfer',
    price: 1341,
    lgt_http: 'https://lgt.ro/oferta-item/now-onyx-punta-cana-5/'
  },
  {
  id: 'offer6355',
    firstImgSrc: 'assets/lgt/offers/offer6355/firstImgSrc/img.png',
    offer_name: 'HARBOR CLUB ST LUCIA, CURIO COLLECTION BY HILTON 4* | ALL INCLUSIVE',
    destination_detail: 'Rodney Bay, Gros Islet, Saint Lucia',
    destination_city_name: 'Saint Lucia',
    destination_type: '',
    revelion: '',
    package_details: 'Pachet St. Lucia - Zbor + Cazare & Masa + Transfer',
    price: 1341,
    lgt_http: 'https://lgt.ro/oferta-item/royalton-riviera-cancun-resort-spa-5/'
  }
];
